### ISSUE TITLE
Save file without !Generated header

### ISSUE THREAD

**Issue by funivan** [makkarpov/scalingua#16]
Hello. 👋 
Is there any way to save file without the `!Generated:` header?

**Comment by makkarpov** [comment]
It could be done, but I'm not actively maintaining this library now. I had transitioned from Play based stack (in which this library was primarily useful) a long time ago.

If you make a PR with that changes (e.g. introducing a separate compile option to configure that) - I will publish it in upstream repository.

**Comment by makkarpov** [comment]
Released as version 1.1. It may take some time for version to sync into central repositories.
